
[book]
authors = ["CnTransGroup"]
language = "zh"
multilingual = false
src = "src"
title = "C++ 17 The Complete Guide"

[output.html]
mathjax-support = true
no-section-label = true
git-repository-url = "https://github.com/CnTransGroup/Cpp17TheCompleteGuideChinese"
git-repository-icon = "fa-github"

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true